### ISSUE TITLE
code and CLIP model weight

### ISSUE THREAD

**Issue by dialogueeeeee** [niki-amini-naieni/CounTX#1]
Thanks for the interesting insights!

Will you be releasing the code and CLIP model weight soon? Thanks in advance!

**Comment by niki-amini-naieni** [comment]
Hello,

Thank you for the message and interest! Yes, both the code and weights will be published in about one and a half weeks. I am commenting and organizing the code so that it is easy to understand.

Best wishes,
Niki

**Comment by niki-amini-naieni** [comment]
Hi @dialogueeeeee, the code and weights from the paper have been posted. Please refer to the main README.md for instructions and feel free to email me at niki.amini-naieni@eng.ox.ac.uk for any further questions.
