### ISSUE TITLE
Test on the CARPK

### ISSUE THREAD

**Issue by wangyutian73** [niki-amini-naieni/CounTX#3]
Thank you for your excellent work, could you please provide the test code of CounTX on the CARPK dataset?

**Comment by niki-amini-naieni** [comment]
Thank you for the kind words! Yes, I will release the test code in a few days and eventually the training code too.

**Comment by niki-amini-naieni** [comment]
Hello, @wangyutian73! I have uploaded the code and pretrained weights to test CounTX on CARPK. The instructions can be found [here](https://github.com/niki-amini-naieni/CounTX/tree/main?tab=readme-ov-file#pre-trained-weights).

**Comment by wangyutian73** [comment]
Thank you for your reply! May I ask about the quantitative results tested on the CARPK dataset?

**Comment by niki-amini-naieni** [comment]
Yes, of course! Below are the results from the paper. Please let me know if you have any specific questions.
<img width="515" alt="image" src="https://github.com/niki-amini-naieni/CounTX/assets/61301874/90d4d355-1edd-4c1e-b4be-757ad16531d1">
