### ISSUE TITLE
code problem

### ISSUE THREAD

**Issue by Haim44** [niki-amini-naieni/CounTX#6]
Hello author!
Thank you very much for your contribution to the scientific research industry. Now, while running your code, in line 126 of modelscounting network.py, the variables img tokens [8512] and fim pos embedded [l, 196512] are "img_tokens=img_tokens+self. fim pos embedded"., Shape mismatch will result in an error message

**Comment by niki-amini-naieni** [comment]
Hi @Haim44, thank you for the kind words!

I just ran the CounTX test code, and it still reproduces the results from the paper with no errors. I think the issue you have is that your image is the wrong size for the CounTX code. 

```fim_pos_embed``` is of size 1 x 196 x 512 because there should be 1 image with 14 x 14 = 196 image tokens each of length 512. However, you seem to have 8 image tokens of length 512. May I ask what image data you are using?

**Comment by Haim44** [comment]
Hello author,
Thank you for your response and explanation. I appreciate your help in clarifying the issue. 
Although I also use the FSC147 dataset, but because it was downloaded in the past, there may be a difference in size, I checked the pictures in the dataset, they are all ***×384 size, and then I will download a copy of FSC147 with the link you provided to try again.Thank you again for your quick reply, which made me feel the warmth of the world.
Good luck on your learning journey！

**Comment by niki-amini-naieni** [comment]
Hi @Haim44,

I am happy to help! Yes, fixing the image sizes could fix your issue. I just used the same images as [CounTR](https://github.com/Verg-Avesta/CounTR).

Good luck, and please let me know if you have any further questions!

**Comment by Haim44** [comment]
Hello author！
It's a pleasure to hear from you again, and after re-downloading the dataset, I found that my newly downloaded dataset is exactly the same as the original one. However, after I changed the batchsize from 8 to 1, the initial error was not reported, and the program was able to run. But I don't know if I'm right.
Thank you again for your generous help!     O(∩_∩)O

**Comment by niki-amini-naieni** [comment]
Hi @Haim44, you are right! The batch size for testing should be 1, while the batch size for training should be 8. The code defaults to this. The test code will not run properly without 1 as the batch size. The training code should be able to accommodate for variable batch sizes.
